### ISSUE TITLE
Gradle-specific getting started guide

### ISSUE THREAD

**Issue by myhau** [VirtuslabRnD/pulumi-kotlin#197]
[Getting started](https://github.com/VirtuslabRnD/pulumi-kotlin#getting-started) guide only covers Maven. 

React with 👍 if you would like to have such guide for Gradle too.

**Comment by algoflows** [comment]
Please support Gradle guide, most new projects are started with Gradle, as a newbie it's easier to find Gradle resources and I am lost at the moment.

**Comment by michal-fudala-ikea** [comment]
Hi @algoflows

Thanks for your feedback! We are going to work on the Gradle guide soon. I'll provide some more updates this week.

**Comment by myhau** [comment]
Hi @algoflows

Thanks for your feedback! We are going to work on the Gradle guide soon. I'll provide some more updates this week.

**Comment by algoflows** [comment]
Super excited for this, have there been any further developments?! :)

**Comment by myhau** [comment]
@algoflows here is the first step towards that: https://github.com/VirtuslabRnD/pulumi-kotlin/pull/224.

Should be good enough for now :). Let me know what you think (by dropping a comment in the PR).
