### ISSUE TITLE
Push artifacts to Maven Central

### ISSUE THREAD

**Issue by myhau** [VirtuslabRnD/pulumi-kotlin#204]
# Context

Authenticating with GitHub Packages might be too much for developer that is "just passing by". 

We need to reduce friction, so that more people can quickly try this out and express their opinion.

# Acceptance criteria

- Existing release scripts support pushing to Maven Central

- All existing packages (with bumped versions) are present in Maven Central repository

- Documentation is updated

  - "Supported providers" table
  - "Getting started" guide

- GitHub Packages pane is not displayed on `pulumi-kotlin` repo page

  
# Details

- docs
  - https://maven.apache.org/repository/guide-central-repository-upload.html
- "hardest" part – domain ownership verification (https://central.sonatype.org/publish/requirements/coordinates/)

**Comment by jplewa** [comment]
The task was officially completed with this PR: https://github.com/VirtuslabRnD/pulumi-kotlin/pull/214
