### ISSUE TITLE
Allow using normal parentheses when calling functions

### ISSUE THREAD

**Issue by myhau** [VirtuslabRnD/pulumi-kotlin#220]
`Functions.getSomething{}` should be `Functions.getSomething()`.

**Comment by jplewa** [comment]
@myhau I believe this has already been done?
<img width="1054" alt="image" src="https://github.com/VirtuslabRnD/pulumi-kotlin/assets/34098778/4f85390d-c9f7-44b4-a492-18d26b2c3297">
