### ISSUE TITLE
Have the Tuple types be a dataclass to allow destructuring

### ISSUE THREAD

**Issue by kylepl** [VirtuslabRnD/pulumi-kotlin#394]
When combining multiple outputs, [Tuples](https://www.pulumi.com/docs/reference/pkg/java/com/pulumi/core/Tuples.Tuple2.html) are useful to do a single `applyValue` on. For instance, right now I write the following, given Output `a` and Output `b`:

```
Output.tuple(a, b).applyValue{ tuple ->
  val a = tuple.t1
  val b = tuple.t2
  // Something complex with a and b
  a + b
}
```

But I would like to write:
```
Output.tuple(a, b).applyValue{ (a, b) ->
  // Something complex with a and b
  a + b
}
```

This helps even more with clarity and brevity as the number of tuple items increase.

**Comment by jplewa** [comment]
For now, those tuple classes are taken from the Java SDK, so we can't turn them into data classes. We can, however, add `component1`/`component2`/etc extension functions, which should also work if you import them 😊

**Comment by kylepl** [comment]
While I'm not sure exactly about the mechanics of importing extension functions, sgtm.
