### ISSUE TITLE
Ease of use of list when using *Builder

### ISSUE THREAD

**Issue by kylepl** [VirtuslabRnD/pulumi-kotlin#396]
A couple related thoughts about how lists work, e.g. for `ServiceSpecArgsBuilder` for k8s. It [has a field `ports`](https://www.pulumi.com/registry/packages/kubernetes/api-docs/core/v1/service/#servicespec), which takes just a list of `ServicePort`, thus is built with `ServicePortArgsBuilder`.

To make this work right now, I am doing:
```
ports(listOf<suspend ServicePortArgsBuilder.() -> Unit>(
  {
    name("https")
    port(443)
    protocol("TCP")
    targetPort(443)
  },
  {
    name("http")
    port(80)
    protocol("TCP")
    targetPort(80)
  }
))
```
but I need to explicitly give a type to the listOf. Without it, it does not try the `suspend ServicePortArgsBuilder.() -> Unit` path, and just fails to compile because (ignoring the shadowing on `name`), `port` is not defined in the outer object.

In the same area, originally I was trying the syntax (which is similar to text protocol buffers) was:
```
ports({
    name("https")
    port(443)
    protocol("TCP")
    targetPort(443)
  })
ports({
    name("http")
    port(80)
    protocol("TCP")
    targetPort(80)
  })
```

but this does not work since it is just a setter, and the last one wins. I'm musing if either this could work (perhaps surprising semantics), or if warning/errors could be shown in these cases (of course, it could be intentional). Not sure.

**Comment by kylepl** [comment]
Annnd I missed the varargs ones, and skimmed to the list ones. It does work great, one I just remove the listOf all together. Thanks!

**Comment by jplewa** [comment]
> Annnd I missed the varargs ones, and skimmed to the list ones. It does work great, one I just remove the listOf all together. Thanks!

No worries, we appreciate the feedback! It's a good point that with several overloads it's easy to miss the most useful one. It might be worth reconsidering if we need all of them in all cases.
