### ISSUE TITLE
Extract `sdk` package to a separate module and release as a separate library

### ISSUE THREAD

**Issue by myhau** [VirtuslabRnD/pulumi-kotlin#41]
It's about `com/virtuslab/pulumikotlin/codegen/sdk`. 

Notes:
- package should match directory structure (it does not currently)
- fully get rid of `toJava` and `toKotlin`??
- get rid of `@JvmName` (or pick better names)
- somehow use `internal`, so that internal methods (e.g. `toJava`) are not visible to the end-user

**Comment by jplewa** [comment]
I would say this should be addressed ASAP. I would suggest creating a Maven package called `org.virtuslab.pulumi-kotlin` and publishing it to Maven Central. It should be published with a separate Gradle task (or it could be extracted to a separate repository). This dependency should be included in each package we publish. We also need to create a Github Action that could be used to publish this package (for now we could trigger it manually)

Here's an example that causes issues:
```kotlin
dependencies {
    implementation("com.pulumi:pulumi:(,1.0]")
    implementation("org.virtuslab:pulumi-gcp-kotlin:6.62.0.0")
    implementation("org.virtuslab:pulumi-docker-kotlin:4.3.0.0")
    implementation("org.virtuslab:pulumi-kubernetes-kotlin:4.1.1.0")
}
```

```kotlin
val kubeconfig = // ...
val clusterProvider = kubernetesProvider("pulumi-kotlin-demo") {
    args {
        kubeconfig(kubeconfig)
    }
}

val namespace = namespace(name) {
    opts {
        provider(clusterProvider)
    }
}
```

This causes issues on `pulumi up` (I cleared my terminal, so I can't paste the error).

The issues disappear when kubernetes is the first dependency.
