### ISSUE TITLE
Add support for the Keycloak provider

### ISSUE THREAD

**Issue by sschuberth** [VirtuslabRnD/pulumi-kotlin#557]
Upstream [Pulumi does support Keycloak](https://www.pulumi.com/registry/packages/keycloak/), so would there be a chance to get a Kotlin "wrapper" here, too?

**Comment by sschuberth** [comment]
That was quick, thank you @jplewa!

**Comment by jplewa** [comment]
@sschuberth Happy to help! It's not released yet, though, I'll ping you when it becomes available in Maven Central :)

**Comment by jplewa** [comment]
@sschuberth Looks like it's been indexed already: https://central.sonatype.com/artifact/org.virtuslab/pulumi-keycloak-kotlin. Let me know if you get a chance to try it out :)

**Comment by sschuberth** [comment]
> @sschuberth Looks like it's been indexed already: https://central.sonatype.com/artifact/org.virtuslab/pulumi-keycloak-kotlin. Let me know if you get a chance to try it out :)

I will! Tough it could take some time, as we're very new to any IaC solution...
