### ISSUE TITLE
Failing to generate components

### ISSUE THREAD

**Issue by jplewa** [VirtuslabRnD/pulumi-kotlin#566]
After updating the Kubernetes schema to `v4.10.0.0`, we get the following error:
<img width="981" alt="image" src="https://github.com/VirtuslabRnD/pulumi-kotlin/assets/34098778/27502ad3-8798-4ff1-804f-656a1b4ba82d">

**Comment by kylepl** [comment]
Can I get confirmation if this is expected to be in the last release of pulumi-kotlin? From https://mvnrepository.com/artifact/org.virtuslab/pulumi-kotlin, there was a release around then, but based on using 0.11.0.0, it seems it is before https://github.com/VirtuslabRnD/pulumi-kotlin/commit/3246756dd37e3224b41fb37d2d628249c2bbb078#diff-5986dc44865c11c212703b730d19eeaf12ccfe8088592d2bc409fd3f2fd600e2, and would love to make use of the new k8s updates.

Thanks!
